

services:
  flask_app:
    container_name: flask_app
    build:
      context: /home/ubuntu/devops/flask-app-ecs/
      dockerfile: Dockerfile-multi-stage     
    ports:
        - "80:80"
    networks:
      - multistage  # ✅ Correct - Use list format

networks:
  multistage:  # ✅ Define networks only once
    driver: bridge
