# Stage 1 From multi-stage docker file

# Step 1 Base Image

FROM python:3.9-slim AS builder

# Step 2 Working Directory

WORKDIR /app

# Step 3 Copy Code from local to container

COPY . .

# Step 4 Install supporting Libraries/ packages
# provide path/target for installtion 

RUN pip install -r requirements.txt --target=/app/deps

################### Stage 2 Multi-Stage-  Distroless Image ######################

# Step1 Distroless Base Image
FROM gcr.io/distroless/python3-debian12

# Step 2 Working Directory

WORKDIR /app
#requirements.txt
# Step 3 Copy code and dependencies from stage 1

COPY --from=builder /app/deps /app/deps

# Copy all code from Stage 1 Step 1 to distroless 

COPY --from=builder /app .

# Environment Varibale where all python dependencies and package installed

ENV PYTHONPATH="/app/deps"



######## This Is from Stage 1 Default Format Of Docker File #############

# Step 5 Expose Port

EXPOSE 80

# Step 6 Serve application for continuous running

CMD ["run.py"]

